# SPDX-FileCopyrightText: 2021 Stefano Babic <sbabic@denx.de>
#
# SPDX-License-Identifier: MIT

ubuntu-jammy:
  image: ubuntu:jammy
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - export TZ=Europe/London
    - apt-get -qq update
    - apt-get install -y build-essential
    - apt-get install -y linux-headers-generic
    - apt-get install -y linux-libc-dev
    - apt-get install -y libyaml-dev
    - apt-get install -y cmake
    - apt-get install -y zlib1g
    - apt-get install -y zlib1g-dev
    - apt-get install -y curl
    - apt-get install -y git
 
  script:
    - if [ ! -d Debug ];then mkdir Debug;fi
    - cd Debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - if [ $CI_COMMIT_BRANCH == "coverity_scan" ]; then
        curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64 --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN;
        tar xfz /tmp/cov-analysis-linux64.tgz;
        cov-analysis-linux64-*/bin/cov-build --dir cov-int make;
        tar cfz cov-int.tar.gz cov-int;
        curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN --form email=$GITLAB_USER_EMAIL --form file=@cov-int.tar.gz --form version="`git describe --tags`" --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID ";
      fi
    - make VERBOSE=1

reuse:
  needs: []
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
